[tool.poetry]
name = "python-dotenv-example"
version = "0.1.0"
description = ""
<<<<<<< HEAD
authors = ["Roed <Geofery10@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
=======
authors = ["anderslatif <anderslatif@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.12"
>>>>>>> main
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
